In [ ]:
import numpy as np

class PCA:
    def __init__(self, n_components):
        self.n_components = n_components
        self.components = None
        self.mean = None
        self.explained_variance = None

    def fit(self, X):
        # Convert input to numpy array
        X = np.array(X)

        # Calculate mean and center the data
        self.mean = np.mean(X, axis=0)
        X_centered = X - self.mean

        # Calculate covariance matrix
        covariance_matrix = np.cov(X_centered.T)  # Fixed: use .T for transpose

        # Compute eigenvalues and eigenvectors
        eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)

        # Sort eigenvalues and eigenvectors in descending order
        sorted_indices = np.argsort(eigenvalues)[::-1]
        sorted_eigenvalues = eigenvalues[sorted_indices]
        sorted_eigenvectors = eigenvectors[:, sorted_indices]

        # Store the top n_components eigenvectors
        self.components = sorted_eigenvectors[:, :self.n_components]

        # Store explained variance
        total_variance = np.sum(sorted_eigenvalues)
        self.explained_variance = sorted_eigenvalues[:self.n_components] / total_variance

    def transform(self, X):
        # Center the data using the stored mean
        X_centered = np.array(X) - self.mean

        # Project data onto principal components
        X_transformed = np.dot(X_centered, self.components)

        return X_transformed

    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)

if __name__ == "__main__":
    # Example data from the screenshot
    X = np.array([
        [4, 8, 13, 7],
        [11, 4, 5, 14],
        [2, 9, 19, 5],
        [7, 6, 10, 8]
    ])

    print("Original data:")
    print(X)

    # Create PCA instance with 2 components
    pca = PCA(n_components=2)

    # Fit PCA to the data
    pca.fit(X)

    # Transform the data
    X_transformed = pca.transform(X)

    print("\nTransformed data (2 principal components):")
    print(X_transformed)

    print("\nExplained variance ratio:")
    print(pca.explained_variance)

Original data:
[[ 4  8 13  7]
 [11  4  5 14]
 [ 2  9 19  5]
 [ 7  6 10  8]]

Transformed data (2 principal components):
[[  2.84441537  -0.75505896]
 [-10.36625221   0.9522929 ]
 [  9.20024675   1.0744314 ]
 [ -1.6784099   -1.27166533]]

Explained variance ratio:
[0.97367618 0.02037655]
